
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Maestro
 */
public class InsertEmployee extends javax.swing.JDialog {

    /**
     * Creates new form InsertHouses
     */
    private final HashMap ht;
    private final Database db;
    private StringBuilder sqlFinal;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JComboBox comboRole;
    private javax.swing.JComboBox comboSup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;

    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton insertButton;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtBirth;
    private javax.swing.JTextField txtHire;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhone;

    public InsertEmployee(java.awt.Frame parent, Database db) {
        super(parent, true);
        this.db = db;
        ht = new HashMap<String, Integer>();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtBirth = new javax.swing.JTextField("MM-DD-YYYY");
        txtHire = new javax.swing.JTextField("MM-DD-YYYY");
        txtSalary = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        comboRole = new javax.swing.JComboBox();
        comboSup = new javax.swing.JComboBox();
        insertButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        confirmarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insert Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fisrt name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Last name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Birth date:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Hire date:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Salary:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Phone:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Role:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Supervisor:");

        txtFname.setColumns(11);
        txtFname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtLname.setColumns(11);
        txtLname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtBirth.setColumns(11);
        txtBirth.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtHire.setColumns(11);
        txtHire.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtSalary.setColumns(11);
        txtSalary.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtEmail.setColumns(11);
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtPhone.setColumns(11);
        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 14));

        comboRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboRole.setModel(new javax.swing.DefaultComboBoxModel(obtenerRoles().toArray(new String[0])));

        comboSup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboSup.setModel(new javax.swing.DefaultComboBoxModel(obtenerSupervisor().toArray(new Integer[0])));

        insertButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insertButton.setText("Insertar");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        confirmarButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformedConfirmar(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformedCancelar(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtFname, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtLname, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtBirth, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtHire, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtSalary, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtPhone, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(comboRole, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(comboSup, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                )
                                .addContainerGap(30, Short.MAX_VALUE))
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(insertButton)
                                .addGap(18)
                                .addComponent(confirmarButton)
                                .addGap(18)
                                .addComponent(cancelButton)
                                .addGap(40))
        );

        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtFname, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtLname, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtBirth, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtHire, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtSalary, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtPhone, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(comboRole, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(comboSup, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(20)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(insertButton)
                                        .addComponent(confirmarButton)
                                        .addComponent(cancelButton))
                                .addGap(20))
        );
        pack();
    }

    private void okButtonActionPerformedCancelar(ActionEvent evt) {
        StringBuilder sql=sqlFinal;
        sql.append(" ");
        sql.append("ROLLBACK;");

        System.out.println( sql.toString() );

        try {
            db.update( sql.toString() );
            JOptionPane.showMessageDialog(this, "Operation canceled");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error");
            System.out.println( ex.getMessage() );
        }
        setVisible(false);
    }

    private void okButtonActionPerformedConfirmar(ActionEvent evt) {
        StringBuilder sql=sqlFinal;
        sql.append(" ");
        sql.append("COMMIT;");

        System.out.println( sql.toString() );

        try {
            db.update( sql.toString() );
            JOptionPane.showMessageDialog(this, "Employee added");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error");
            System.out.println( ex.getMessage() );
        }
        setVisible(false);
    }


    // End of variables declaration//GEN-END:variables

    private ArrayList<String> obtenerRoles() {
        ArrayList<String> roles = new ArrayList<>();
        try {
            // Ejecutar consulta
            ResultSet rs = db.query("SELECT DISTINCT role_name FROM ref_roles ORDER BY role_name ASC");

            // Limpiar combo antes de llenarlo
            comboRole.removeAllItems();

            // Recorrer resultados y agregar al combo
            while (rs.next()) {
                roles.add(rs.getString("role_name"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar supervisores: " + e.getMessage());
        }
        return roles;
    }

    private ArrayList<Integer> obtenerSupervisor() {
        ArrayList<Integer> sup = new ArrayList<>();
        try {
            // Ejecutar consulta
            ResultSet rs = db.query("SELECT DISTINCT employee_id FROM employees WHERE employee_id=1 or employee_id=2 or employee_id=3");

            // Limpiar combo antes de llenarlo
            comboSup.removeAllItems();

            // Recorrer resultados y agregar al combo
            while (rs.next()) {
                sup.add(rs.getInt("employee_id"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar supervisores: " + e.getMessage());
        }
        return sup;
    }

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        String fname = txtFname.getText();
        String lname = txtLname.getText();
        String birth = txtBirth.getText();
        String hiredate = txtHire.getText();
        double salary = Double.parseDouble(txtSalary.getText());
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        String role = (String) comboRole.getSelectedItem();
        int supervisor = (Integer) comboSup.getSelectedItem();

        StringBuilder sql
                = new StringBuilder("BEGIN; INSERT INTO employees (first_name, last_name, date_of_birth, hire_date, salary, email, phone_number, role_code, supervisor_id) " +
                "VALUES (\'");
        sql.append(fname);
        sql.append("\',");
        sql.append("\'");
        sql.append(lname);
        sql.append("\',");
        sql.append("\'");
        sql.append(birth);
        sql.append("\',");
        sql.append("\'");
        sql.append(hiredate);
        sql.append("\',");
        sql.append(salary);
        sql.append(",");
        sql.append("\'");
        sql.append(email);
        sql.append("\',");
        sql.append("\'");
        sql.append(phone);
        sql.append("\',");
        sql.append("(select role_code from ref_roles where role_name='"+role+"')");
        sql.append(",");
        sql.append(supervisor);
        sql.append(");");

        sqlFinal=sql;
        JOptionPane.showMessageDialog(this, "Datos listos para insertar");
    }

}
